name: parkme
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

#  Android Studio Ladybug | 2024.2.1
#  Flutter version 3.24.3 stable
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_maps_flutter: ^2.9.0
#  splashscreen:
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  google_sign_in: ^6.2.1
  qr_flutter: ^4.1.0
  cloud_firestore: ^5.4.4
  razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.8
  carousel_slider: ^5.0.0
  twilio_flutter: ^0.9.0
  intl: ^0.19.0

  geocoding: ^3.0.0
  device_info_plus: ^11.1.0
  platform_info: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/